name: Build

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04,macos-13,macos-14,windows-2019]
        os: [macos-14,windows-2019]
        include:
          - os: windows-2019
            vtk_url: "https://www.vtk.org/files/release/9.3/vtk-wheel-sdk-9.3.1-cp310-cp310-win_amd64.tar.xz"
          - os: macos-14
            vtk_url: "https://www.vtk.org/files/release/9.3/vtk-wheel-sdk-9.3.1-cp310-cp310-macosx_11_0_arm64.tar.xz"

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Create directory for VTK install
        run: |
          mkdir -p ./be/install/vtk

      - name: Download VTK binary
        run: |
          curl -L ${{ matrix.vtk_url }} -o ./be/install/vtk/vtk-wheel-sdk.tar.xz

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Extract VTK binary
        run: |
          tar -xJvf ./be/install/vtk/vtk-wheel-sdk.tar.xz -C ./be/install/vtk

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
            CIBW_ARCHS_LINUX: x86_64
            CIBW_ARCHS_WINDOWS: AMD64
            CIBW_SKIP: "*musllinux*"
            CIBW_BUILD_VERBOSITY: 1
            CIBW_BEFORE_ALL: bash .github/workflows/prebuild.sh
            CIBW_BEFORE_ALL_WINDOWS: powershell .github/workflows/prebuild_win.bat AMD64
            CIBW_ENVIRONMENT: >
                FETCH_DEPENDENCIES=OFF CMAKE_PREFIX_PATH=be/install

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
